spring:
  application:
    name: ai-interview-backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5434/ai_interview_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 4040

app:
  jwt:
    secret: ${JWT_SECRET:xxxx}
    expiration-ms: 86400000
  python-ai-service:
    url: ${PYTHON_AI_URL:http://localhost:8001}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  aws:
    bucket: ${AWS_S3_BUCKET:ai-interview-resumes-prod}
    region: ${AWS_REGION:ap-south-1}
    access-key: ${AWS_ACCESS_KEY_ID:xxxx}
    secret-key: ${AWS_SECRET_ACCESS_KEY:xxxx}
  sendgrid:
    api-key: ${SENDGRID_API_KEY:}
    from-email: noreply@aiinterview.com
    from-name: AI Interview Platform
