spring:
  application:
    name: ai-interview-backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5434}/${PGDATABASE:ai_interview_db}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 4040

app:
  jwt:
    secret: ${JWT_SECRET:ai-interview-platform-dev-secret-key-minimum-256-bits-long}
    expiration-ms: 86400000
    access-token-expiration-ms: 900000
    refresh-token-expiration-days: 7
  python-ai-service:
    url: ${PYTHON_AI_URL:http://localhost:8001}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  aws:
    bucket: ${AWS_S3_BUCKET:ai-interview-resumes-prod}
    region: ${AWS_REGION:ap-south-1}
    access-key: ${AWS_ACCESS_KEY_ID:AKIA46XDEX55FSSDHMVP}
    secret-key: ${AWS_SECRET_ACCESS_KEY:xxxx}
  sendgrid:
    api-key: ${SENDGRID_API_KEY:xxxx}
    from-email: noreply@aiinterview.com
    from-name: AI Interview Platform
